name: NovelEngine
version: ${project.version}-${git.commit.id.describe-short}
authors: [_Fleek, Super_, Mafrans, serrif, falceso, taahanis, Paldiu]
main: net.novelmc.novelengine.NovelEngine
api-version: 1.13
description: A plugin for the NovelMC server
website: novelmc.net
